ALTER TABLE Products
ADD HanSuDung DATETIME NULL;
GO
UPDATE Products
SET HanSuDung = DATEADD(DAY, 120, GETDATE())
WHERE MaSP IN (1, 2, 3, 4, 5, 6, 7);

UPDATE Products
SET HanSuDung = DATEADD(DAY, -5, GETDATE())
WHERE MaSP IN (10, 11);

UPDATE Products
SET HanSuDung = DATEADD(DAY, 10, GETDATE())
WHERE MaSP IN (12, 13);
GO